/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import CLASES.ClassAlumno;
import CLASES.ClassApoderado;
import CLASES.ClassFunciones;
import CLASES.Principal;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class BuscarFamilia extends javax.swing.JInternalFrame {

   String[] cabecera={"IdAlumno","Nombres","Apellidos","Sexo","Dni","Nivel ","Grado","IdApoderado"
            ,"Nombres","Apellidos","Sexo","Dni","Celular","Direccion",};

    ClassAlumno alumnoSelec= new ClassAlumno();
    ClassApoderado apoderadoSelec=new ClassApoderado();
    ClassFunciones buscar=new ClassFunciones();
    DefaultTableModel modelito2=new DefaultTableModel(cabecera,Principal.alumnos.size());
    
    public BuscarFamilia() {
        initComponents();
        transparencia();
        llenarTabla();
    }
    public void transparencia(){
        btnBuscar.setOpaque(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setBorderPainted(false);
        
        btnSeleccionar.setOpaque(false);
        btnSeleccionar.setContentAreaFilled(false);
        btnSeleccionar.setBorderPainted(false);
        
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false); 
    }
    
    
    private void llenarTabla(){
        //Generados el modelo de la tabla
     //   DefaultTableModel modelito=new DefaultTableModel(cabecera,Principal.apoderados.size());
        tablaFamilia.setModel(modelito2);
        TableModel modeloDatosFamiliaBuscando=tablaFamilia.getModel();
        for(int i=0;i<Principal.alumnos.size();i++){
            ClassAlumno alumno=Principal.alumnos.get(i);
            //fila i- columna 0
            modeloDatosFamiliaBuscando.setValueAt(alumno.getIdAlumno(),i,0);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getNombres(),i,1);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApellidos(),i,2);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getSexo(),i,3);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getDni(),i,4);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getNivel(),i,5);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getGrado(),i,6);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApoderado().getIdApoderado(),i,7);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApoderado().getNombres(),i,8);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApoderado().getApellidos(),i,9);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApoderado().getSexo(),i,10);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApoderado().getDni(),i,11);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApoderado().getCelular(),i,12);
            modeloDatosFamiliaBuscando.setValueAt(alumno.getApoderado().getDireccion(),i,13);
            
            
        } 
    }
    
    void limpiaMatriz() {
        for(int i=0;i<Principal.alumnos.size();i++){
            tablaFamilia.setValueAt("",i,0);
            tablaFamilia.setValueAt("",i,1);
            tablaFamilia.setValueAt("",i,2);
            tablaFamilia.setValueAt("",i,3);
            tablaFamilia.setValueAt("",i,4);
            tablaFamilia.setValueAt("",i,5);
            tablaFamilia.setValueAt("",i,6);
            tablaFamilia.setValueAt("",i,7);
            tablaFamilia.setValueAt("",i,8);
            tablaFamilia.setValueAt("",i,9);
            tablaFamilia.setValueAt("",i,10);
            tablaFamilia.setValueAt("",i,11);
            tablaFamilia.setValueAt("",i,12);
            tablaFamilia.setValueAt("",i,13);
           
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFamilia = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        txtBuscarNombre = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(null);

        tablaFamilia.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        tablaFamilia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFamilia);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 1110, 550);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_undo_26px.png"))); // NOI18N
        btnRegresar.setToolTipText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(1060, 10, 60, 40);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Familia");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 30, 190, 29);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setText("Buscar por Nombre:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 89, 160, 30);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_26px.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(430, 90, 60, 40);

        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_checked_radio_button_48px_1.png"))); // NOI18N
        btnSeleccionar.setToolTipText("Seleccionar un apoderado de la lista.");
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionar);
        btnSeleccionar.setBounds(1000, 80, 70, 50);

        txtBuscarNombre.setBackground(new java.awt.Color(208, 213, 255));
        txtBuscarNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtBuscarNombre.setBorder(null);
        getContentPane().add(txtBuscarNombre);
        txtBuscarNombre.setBounds(190, 90, 180, 30);

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(530, 60, 190, 20);

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator13);
        jSeparator13.setBounds(200, 130, 200, 20);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccionar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(990, 140, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/morado_x1000.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1140, 770);

        setBounds(0, 0, 1134, 761);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try{
            limpiaMatriz();
            String dniAlumno = txtBuscarNombre.getText();
            ClassAlumno busq = buscar.nombreFamilia(dniAlumno);

            if (busq != null){

                tablaFamilia.setValueAt(busq.getIdAlumno(),0,0);
                tablaFamilia.setValueAt(busq.getNombres(),0,1);
                tablaFamilia.setValueAt(busq.getApellidos(),0,2);
                tablaFamilia.setValueAt(busq.getSexo(),0,3);
                tablaFamilia.setValueAt(busq.getDni(),0,4);
                tablaFamilia.setValueAt(busq.getNivel(),0,5);
                tablaFamilia.setValueAt(busq.getGrado(),0,6);
                tablaFamilia.setValueAt(busq.getApoderado().getIdApoderado(),0,7);
                tablaFamilia.setValueAt(busq.getApoderado().getNombres(),0,8);
                tablaFamilia.setValueAt(busq.getApoderado().getApellidos(),0,9);
                tablaFamilia.setValueAt(busq.getApoderado().getSexo(),0,10);
                tablaFamilia.setValueAt(busq.getApoderado().getDni(),0,11);
                tablaFamilia.setValueAt(busq.getApoderado().getCelular(),0,12);
                tablaFamilia.setValueAt(busq.getApoderado().getDireccion(),0,13);

            }else{
                llenarTabla();
                JOptionPane.showMessageDialog(null, "Apoderado NO encontrado",
                    "Confirmacion", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error de Entrada de Datos",
                "Confirmacion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        if(tablaFamilia.getSelectedRow()>=0){
            try{

                DefaultTableModel tm = (DefaultTableModel)tablaFamilia.getModel();
                String IDALUM= String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),0));
                String NOMBREALUM=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),1));
                String APEALUM=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),2));
                String SEALUM=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),3));
                int DNIALUM=Integer.parseInt(String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),4)));
                String NIVALUM=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),5));
                String GRADALUM=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),6));
                String IDAPO=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),7));
                String NOMBREAPO=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),8));
                String APEAPO=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),9));
                String SEAPO=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),10));
                int DNIAPO =Integer.parseInt(String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),11)));
                int CELAPO=Integer.parseInt(String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),12)));
                String DIRECAPO=String.valueOf(tm.getValueAt(tablaFamilia.getSelectedRow(),13));

                Caja.txtNombreAlumno.setText(NOMBREALUM);
                Caja.txtNombreResponsable.setText(NOMBREAPO);
                Caja.txtNivelAlu.setText(NIVALUM);
                Caja.txtGradoAlu.setText(GRADALUM);

                alumnoSelec.setNombres(NOMBREALUM);
                alumnoSelec.setIdAlumno(IDALUM);
                alumnoSelec.setApellidos(APEALUM);
                alumnoSelec.setSexo(SEALUM);
                alumnoSelec.setDni(DNIALUM);
                alumnoSelec.setGrado(GRADALUM);
                alumnoSelec.setNivel(NIVALUM);

                apoderadoSelec.setIdApoderado(IDAPO);
                apoderadoSelec.setApellidos(APEAPO);
                apoderadoSelec.setSexo(SEAPO);
                apoderadoSelec.setCelular(CELAPO);
                apoderadoSelec.setDireccion(DIRECAPO);
                apoderadoSelec.setNombres(NOMBREAPO);
                apoderadoSelec.setDni(DNIAPO);

                this.dispose();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"NO EXISTEN DATOS");
            }

        }else{
            JOptionPane.showMessageDialog(this,"DEBE SELECCIONAR UNA FAMILIA","SISTEMA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    public static javax.swing.JTable tablaFamilia;
    private javax.swing.JTextField txtBuscarNombre;
    // End of variables declaration//GEN-END:variables
}
