/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class CrearConcepto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearConcepto
     */
    public CrearConcepto() {
        initComponents();
        transparencia();
    }
    
    public void transparencia(){
        btnGuardar.setOpaque(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setBorderPainted(false);

        
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
 
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtAgregarConcepto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 248, 243));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/21.png"))); // NOI18N

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(null);

        txtAgregarConcepto.setBackground(new java.awt.Color(250, 213, 229));
        txtAgregarConcepto.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtAgregarConcepto.setBorder(null);
        txtAgregarConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarConceptoKeyTyped(evt);
            }
        });
        getContentPane().add(txtAgregarConcepto);
        txtAgregarConcepto.setBounds(150, 120, 170, 30);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descripción:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 100, 30);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear Concepto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 30, 180, 29);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_save_48px.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(360, 110, 60, 50);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_undo_26px.png"))); // NOI18N
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(400, 10, 50, 40);

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator11);
        jSeparator11.setBounds(140, 160, 190, 20);

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(140, 60, 190, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/25.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 460, 270);

        setBounds(0, 0, 458, 291);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgregarConceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarConceptoKeyTyped
        char c = evt.getKeyChar();
        if((c<'a'||c>'z') &&(c<'A'||c>'Z') && c!=KeyEvent.VK_SPACE)evt.consume();
    }//GEN-LAST:event_txtAgregarConceptoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        CrearDeuda.cbTipoConcepto.addItem(txtAgregarConcepto.getText());
        JOptionPane.showMessageDialog(null,"Concepto agregado exitosamente");
        this.dispose();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JTextField txtAgregarConcepto;
    // End of variables declaration//GEN-END:variables
}
