/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import CLASES.ClassApoderado;
import CLASES.Principal;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Formularios.Menú;

import CLASES.ClassApoderado;
import CLASES.Principal;
import static Formularios.Menú.escritorio;
import java.io.File;
import java.util.Formatter;

/**
 *
 * @author Usuario
 */
public class DatosApoderado extends javax.swing.JInternalFrame {

     boolean registrar;
     public boolean mostrar=false;
   // int idApoderado;
    protected ClassApoderado modificar;// al principio estara nula
    ClassApoderado apoderado;
    
    public DatosApoderado() {
        initComponents();
        transparencia();
        limpiarTextosApoderado();
        textosApoderado(false);
        controlesApoderado(true);
    }

    
    public void transparencia(){
        btnCancelarApoderado.setOpaque(false);
        btnCancelarApoderado.setContentAreaFilled(false);
        btnCancelarApoderado.setBorderPainted(false);
        
        btnEliminarApoderado.setOpaque(false);
        btnEliminarApoderado.setContentAreaFilled(false);
        btnEliminarApoderado.setBorderPainted(false);
        
        btnModificarApoderado.setOpaque(false);
        btnModificarApoderado.setContentAreaFilled(false);
        btnModificarApoderado.setBorderPainted(false);
        
        btnNuevoApoderado.setOpaque(false);
        btnNuevoApoderado.setContentAreaFilled(false);
        btnNuevoApoderado.setBorderPainted(false);
        
        btnRegistrarApoderado.setOpaque(false);
        btnRegistrarApoderado.setContentAreaFilled(false);
        btnRegistrarApoderado.setBorderPainted(false);
        
        btnReporteApoderado.setOpaque(false);
        btnReporteApoderado.setContentAreaFilled(false);
        btnReporteApoderado.setBorderPainted(false);
        
        
    }
    
    String barrn = File.separator;
    String CrearUbicacion = System.getProperty("user.dir") + barrn + "ApoderadoTXT" + barrn;

    private void crear() {
        String archivo = getidApoderado() + ".txt";
        File CrearUbi = new File(CrearUbicacion);
        File CrearArchi = new File(CrearUbicacion + archivo);

        try {
            CrearUbi.mkdirs();
            Formatter CrearForma = new Formatter(CrearUbicacion + archivo);

            CrearForma.format("%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n", "ID= " + getidApoderado(),
                    "NOMBRE= " + getNombresApoderado(), "APELLIDO= "
                    + getApellidosApoderado(), "CELULAR= " + getCelularApoderado(),
                    "DNI= " + getDniApoderado(), "DIRECCION= " + getDireccionApoderado(), "SEXO= " + getSexoApoderado());
            CrearForma.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Registro incorrecto");
        }

    }

    
    String getidApoderado(){
        
        return "AP00"+(Principal.apoderados.size()+100);
    }
    String getNombresApoderado(){return txtNombresApoderado.getText();}
    String getApellidosApoderado(){return txtApellidosApoderado.getText();}
    int getCelularApoderado(){return Integer.parseInt(txtCelularApoderado.getText());}
    String getDireccionApoderado(){return txtDireccionApoderado.getText();}
    int getDniApoderado(){return Integer.parseInt(txtDniApoderado.getText());}
    String getSexoApoderado(){return cboSexoApoderado.getSelectedItem().toString();}
    
    
    
    void limpiarTextosApoderado(){
      
        txtNombresApoderado.setText("");
        txtApellidosApoderado.setText("");
        txtCelularApoderado.setText("");
        txtDniApoderado.setText("");
        txtDireccionApoderado.setText("");
        cboSexoApoderado.setSelectedIndex(0);
    }
   void textosApoderado(boolean tf){
    
        txtNombresApoderado.setEditable(tf);
        txtApellidosApoderado.setEditable(tf);
        txtCelularApoderado.setEditable(tf);
        cboSexoApoderado.setEnabled(tf);
        txtDniApoderado.setEditable(tf);
        txtDireccionApoderado.setEditable(tf);
        
    }
    void controlesApoderado(boolean tf){
        btnNuevoApoderado.setEnabled(tf);
        btnRegistrarApoderado.setEnabled(!tf);
        btnCancelarApoderado.setEnabled(!tf);
        btnModificarApoderado.setEnabled(tf);
        btnEliminarApoderado.setEnabled(tf);
        btnReporteApoderado.setEnabled(tf);
       // btnBuscar.setEnabled(tf);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDniApoderado = new javax.swing.JTextField();
        txtDireccionApoderado = new javax.swing.JTextField();
        txtCelularApoderado = new javax.swing.JTextField();
        txtApellidosApoderado = new javax.swing.JTextField();
        txtNombresApoderado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        btnNuevoApoderado = new javax.swing.JButton();
        btnRegistrarApoderado = new javax.swing.JButton();
        btnCancelarApoderado = new javax.swing.JButton();
        btnEliminarApoderado = new javax.swing.JButton();
        btnReporteApoderado = new javax.swing.JButton();
        btnModificarApoderado = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        cboSexoApoderado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbModificar = new javax.swing.JLabel();
        lbNuevo = new javax.swing.JLabel();
        lbRegistrar = new javax.swing.JLabel();
        lbReporte = new javax.swing.JLabel();
        lbEliminar = new javax.swing.JLabel();
        lbCancelar = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registro del Apoderado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 70, 290, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_school_director_male_skin_type_7_64px.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 110, 110, 110);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Celular");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 350, 200, 40);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dirección");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 350, 210, 40);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Apellidos");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 220, 200, 40);

        txtDniApoderado.setBackground(new java.awt.Color(206, 236, 255));
        txtDniApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtDniApoderado.setBorder(null);
        txtDniApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniApoderadoActionPerformed(evt);
            }
        });
        txtDniApoderado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniApoderadoKeyTyped(evt);
            }
        });
        getContentPane().add(txtDniApoderado);
        txtDniApoderado.setBounds(360, 560, 230, 50);

        txtDireccionApoderado.setBackground(new java.awt.Color(206, 236, 255));
        txtDireccionApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtDireccionApoderado.setBorder(null);
        getContentPane().add(txtDireccionApoderado);
        txtDireccionApoderado.setBounds(370, 400, 220, 50);

        txtCelularApoderado.setBackground(new java.awt.Color(206, 236, 255));
        txtCelularApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtCelularApoderado.setBorder(null);
        txtCelularApoderado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularApoderadoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCelularApoderado);
        txtCelularApoderado.setBounds(70, 400, 220, 50);

        txtApellidosApoderado.setBackground(new java.awt.Color(206, 236, 255));
        txtApellidosApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtApellidosApoderado.setBorder(null);
        txtApellidosApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosApoderadoActionPerformed(evt);
            }
        });
        txtApellidosApoderado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosApoderadoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidosApoderado);
        txtApellidosApoderado.setBounds(360, 270, 250, 50);

        txtNombresApoderado.setBackground(new java.awt.Color(206, 236, 255));
        txtNombresApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNombresApoderado.setBorder(null);
        txtNombresApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresApoderadoActionPerformed(evt);
            }
        });
        txtNombresApoderado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresApoderadoKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombresApoderado);
        txtNombresApoderado.setBounds(60, 270, 230, 50);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dni");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 500, 210, 50);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nombres");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 220, 190, 40);

        jSeparator8.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator8.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(50, 620, 250, 20);

        btnNuevoApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnNuevoApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_new_40px.png"))); // NOI18N
        btnNuevoApoderado.setToolTipText("Nuevo");
        btnNuevoApoderado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNuevoApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoApoderado);
        btnNuevoApoderado.setBounds(30, 690, 150, 80);

        btnRegistrarApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnRegistrarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_add_user_group_woman_man_48px.png"))); // NOI18N
        btnRegistrarApoderado.setToolTipText("Registrar");
        btnRegistrarApoderado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistrarApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarApoderado);
        btnRegistrarApoderado.setBounds(30, 820, 150, 80);

        btnCancelarApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCancelarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_40px.png"))); // NOI18N
        btnCancelarApoderado.setToolTipText("Cancelar");
        btnCancelarApoderado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancelarApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarApoderado);
        btnCancelarApoderado.setBounds(440, 820, 150, 80);

        btnEliminarApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnEliminarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trash_48px_1.png"))); // NOI18N
        btnEliminarApoderado.setToolTipText("Eliminar");
        btnEliminarApoderado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminarApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarApoderado);
        btnEliminarApoderado.setBounds(240, 820, 150, 80);

        btnReporteApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnReporteApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_file_submodule_40px.png"))); // NOI18N
        btnReporteApoderado.setToolTipText("Reporte");
        btnReporteApoderado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReporteApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporteApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteApoderado);
        btnReporteApoderado.setBounds(450, 690, 140, 80);

        btnModificarApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnModificarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_pencil_40px.png"))); // NOI18N
        btnModificarApoderado.setToolTipText("Modificar");
        btnModificarApoderado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnModificarApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarApoderado);
        btnModificarApoderado.setBounds(240, 690, 150, 80);

        jSeparator9.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator9.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(350, 460, 260, 20);

        jSeparator10.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator10.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(350, 620, 260, 20);

        jSeparator11.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator11.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator11);
        jSeparator11.setBounds(50, 330, 250, 20);

        jSeparator12.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator12.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(350, 330, 260, 20);

        jSeparator14.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator14.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator14);
        jSeparator14.setBounds(50, 460, 250, 20);

        cboSexoApoderado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cboSexoApoderado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Masculino", "Femenino" }));
        cboSexoApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(cboSexoApoderado);
        cboSexoApoderado.setBounds(70, 550, 200, 50);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sexo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 490, 210, 50);

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator13);
        jSeparator13.setBounds(190, 100, 290, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apoderado 750x950.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 0, 740, 950);

        lbModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbModificar);
        lbModificar.setBounds(270, 770, 90, 30);

        lbNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbNuevo);
        lbNuevo.setBounds(60, 770, 90, 30);

        lbRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbRegistrar);
        lbRegistrar.setBounds(60, 900, 90, 30);

        lbReporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbReporte);
        lbReporte.setBounds(480, 770, 80, 30);

        lbEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbEliminar);
        lbEliminar.setBounds(270, 900, 100, 30);

        lbCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbCancelar);
        lbCancelar.setBounds(470, 900, 90, 30);

        jCheckBox1.setBackground(new java.awt.Color(206, 236, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Mostrar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(60, 640, 130, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 950);

        setBounds(0, 0, 1400, 971);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresApoderadoActionPerformed

    private void btnNuevoApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoApoderadoActionPerformed

        registrar=true;
        limpiarTextosApoderado();
        textosApoderado(true);
        controlesApoderado(false);
        //   txtidApoderado.requestFocus();
    }//GEN-LAST:event_btnNuevoApoderadoActionPerformed

    private void btnRegistrarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarApoderadoActionPerformed
    crear();
        if(registrar){
            try{
                if(txtNombresApoderado.getText().isEmpty() || txtApellidosApoderado.getText().isEmpty()
                    || txtDniApoderado.getText().isEmpty()||txtCelularApoderado.getText().isEmpty() || txtDireccionApoderado.getText().isEmpty()
                    || cboSexoApoderado.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"Completa todos los datos");
                    return;
                }else{
                    apoderado= new ClassApoderado(getidApoderado(),getCelularApoderado(),getDireccionApoderado(),
                        getNombresApoderado(),getApellidosApoderado(), getDniApoderado(), getSexoApoderado());
                    apoderado.setIdApoderado(getidApoderado());
                    apoderado.setCelular(getCelularApoderado());
                    apoderado.setDireccion(getDireccionApoderado());
                    apoderado.setNombres(getNombresApoderado());
                    apoderado.setApellidos(getApellidosApoderado());
                    apoderado.setDni(getDniApoderado());
                    apoderado.setSexo(getSexoApoderado());
                    JOptionPane.showMessageDialog(this,"Apoderado registrado con el id: "+(getidApoderado()));
                    Principal.apoderados.add(apoderado);
                }
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
        else{
            try{
                modificar.setNombres(getNombresApoderado());
                modificar.setApellidos(getApellidosApoderado());
                modificar.setCelular(getCelularApoderado());
                modificar.setDireccion(getDireccionApoderado());
                modificar.setDni(getDniApoderado());
                //  modificar.setIdApoderado(getidApoderado());

                modificar.setSexo(getSexoApoderado());
                JOptionPane.showMessageDialog(this, "El apoderado se a modificado correctamente..");
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
        limpiarTextosApoderado();
        textosApoderado(false);
        controlesApoderado(true);
    }//GEN-LAST:event_btnRegistrarApoderadoActionPerformed

    private void btnCancelarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarApoderadoActionPerformed

        limpiarTextosApoderado();
        textosApoderado(false);
        controlesApoderado(true);
    }//GEN-LAST:event_btnCancelarApoderadoActionPerformed

    private void btnEliminarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarApoderadoActionPerformed

        String aaron=(JOptionPane.showInputDialog(this,"Ingrese Id del apoderado a Eliminar:","Eliminar",JOptionPane.OK_CANCEL_OPTION));
        int i=-1; // si realmente se encontro o no el id
        // recorremos la lista de apoderados
        //for(int j=0;j<Principal.apoderados.size();j++){

            //Busca el dato
            for(int j=0;j<Principal.apoderados.size();j++){
                if(Principal.apoderados.get(j).getIdApoderado().equalsIgnoreCase(aaron)){
                    i=j;
                    break;
                }
            }
            // una vez encontrado el dato->
            ///
            if(i>=0){// si no es -1 significa q si tenemos que eliminar

                int resp = JOptionPane.showConfirmDialog(this,"Deseas Eliminarlo ","Eliminar Dato",JOptionPane.YES_NO_OPTION );

                if(resp == JOptionPane.YES_OPTION){
                    JOptionPane.showMessageDialog(this,"Registro eliminado");
                    Principal.apoderados.remove(i);
                }
                if(resp == JOptionPane.NO_OPTION){
                    JOptionPane.showMessageDialog(this,"cancelando..");
                }

            }
            else {
                try{
                    if(aaron.equals(null)){}
                    else JOptionPane.showMessageDialog(this,"Error en la entrada de datos");
                }
                catch(Exception e){JOptionPane.showMessageDialog(null,"Cancelando procedimiento","Mensaje",JOptionPane.ERROR_MESSAGE);}
            }

    }//GEN-LAST:event_btnEliminarApoderadoActionPerformed

    private void btnReporteApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteApoderadoActionPerformed
        
        ListaApoderado frm3=new ListaApoderado();
        escritorio.add(frm3);
        frm3.show();
        
    }//GEN-LAST:event_btnReporteApoderadoActionPerformed

    private void txtDniApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniApoderadoActionPerformed

    private void txtNombresApoderadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresApoderadoKeyTyped
        
        char c = evt.getKeyChar();
        if((c<'a'||c>'z') &&(c<'A'||c>'Z') && c!=KeyEvent.VK_SPACE && (c!='ñ')
           && (c!='Ñ') && (c!='á') && (c!='é') && (c!='í') && (c!='ó') && (c!='ú'))evt.consume();
      
    }//GEN-LAST:event_txtNombresApoderadoKeyTyped

    private void txtApellidosApoderadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosApoderadoKeyTyped
        
        char c = evt.getKeyChar();
        if((c<'a'||c>'z') &&(c<'A'||c>'Z') && c!=KeyEvent.VK_SPACE && (c!='ñ')
           && (c!='Ñ') && (c!='á') && (c!='é') && (c!='í') && (c!='ó') && (c!='ú'))evt.consume();
        
    }//GEN-LAST:event_txtApellidosApoderadoKeyTyped

    private void txtDniApoderadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniApoderadoKeyTyped
        
        char c = evt.getKeyChar();
       if((c<'0'||c>'9') && c!=KeyEvent.VK_SPACE)evt.consume();
       
    }//GEN-LAST:event_txtDniApoderadoKeyTyped

    private void txtCelularApoderadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularApoderadoKeyTyped
        
        char c = evt.getKeyChar();
       if((c<'0'||c>'9') && c!=KeyEvent.VK_SPACE)evt.consume();
       
    }//GEN-LAST:event_txtCelularApoderadoKeyTyped

    private void btnModificarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarApoderadoActionPerformed
        ///////////////buscar/////////////////
        modificar=null;
        String enrique;
        enrique=(JOptionPane.showInputDialog(this,"Ingrese Id del apoderado a modificar:","Modificar",JOptionPane.OK_CANCEL_OPTION));
        for(ClassApoderado a: Principal.apoderados){
            if(a.getIdApoderado().equalsIgnoreCase(enrique)){
                modificar=a;
                break;
            }
        }
        if(modificar!=null){// si no esta vacio es porque si existe
            //modificar.getIdApoderado();//////////////////////////////////////////////////////

            // registrar=false;
            int resp = JOptionPane.showConfirmDialog(this,"Modificar?","Modificar Dato",JOptionPane.YES_NO_OPTION );
            txtNombresApoderado.setText(modificar.getNombres());
            txtApellidosApoderado.setText(modificar.getApellidos());
            txtCelularApoderado.setText(String.valueOf(modificar.getCelular()));
            txtDireccionApoderado.setText(modificar.getDireccion());
            txtDniApoderado.setText(String.valueOf(modificar.getDni()));
            cboSexoApoderado.setSelectedItem(modificar.getSexo());
            if(resp == JOptionPane.YES_OPTION){
                ///////////////modificar//////////////////////////

                textosApoderado(true);
                controlesApoderado(false);
                registrar=false;
            }
            if(resp == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(this,"cancelando..");
            }
        }
        else{
            try{
                if(enrique.equals(null)){}
                else JOptionPane.showMessageDialog(this,"Error en la entrada de datos");
            }
            catch(Exception e){JOptionPane.showMessageDialog(null,"Cancelando procedimiento","Mensaje",JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btnModificarApoderadoActionPerformed

    private void txtApellidosApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosApoderadoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
        if(mostrar){
        lbCancelar.setText("");
        lbEliminar.setText("");
        lbModificar.setText("");
        lbNuevo.setText("");
        lbRegistrar.setText("");
        lbReporte.setText("");
        mostrar=false;
        }else{
        lbCancelar.setText("Cancelar");
        lbEliminar.setText("Eliminar");
        lbModificar.setText("Modificar");
        lbNuevo.setText("Nuevo");
        lbRegistrar.setText("Registrar");
        lbReporte.setText("Reporte");
        mostrar=true;
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarApoderado;
    private javax.swing.JButton btnEliminarApoderado;
    private javax.swing.JButton btnModificarApoderado;
    private javax.swing.JButton btnNuevoApoderado;
    private javax.swing.JButton btnRegistrarApoderado;
    private javax.swing.JButton btnReporteApoderado;
    private javax.swing.JComboBox<String> cboSexoApoderado;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbCancelar;
    private javax.swing.JLabel lbEliminar;
    private javax.swing.JLabel lbModificar;
    private javax.swing.JLabel lbNuevo;
    private javax.swing.JLabel lbRegistrar;
    private javax.swing.JLabel lbReporte;
    private javax.swing.JTextField txtApellidosApoderado;
    private javax.swing.JTextField txtCelularApoderado;
    private javax.swing.JTextField txtDireccionApoderado;
    private javax.swing.JTextField txtDniApoderado;
    private javax.swing.JTextField txtNombresApoderado;
    // End of variables declaration//GEN-END:variables
}
