/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {
    
    public boolean mostrar=false;
    int x,y;
    
    public Login() {
        
        initComponents();
        setLocationRelativeTo(null);
        txtcontraseñaVisible.setVisible(true);
        txtcontraseñaOculta.setVisible(false);
        transparencia();
        
    }
    public void transparencia(){
        btnIngresar.setOpaque(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setBorderPainted(true);
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcontraseñaVisible = new javax.swing.JPasswordField();
        txtcontraseñaOculta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(null);

        txtusuario.setBackground(new java.awt.Color(208, 213, 255));
        txtusuario.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        txtusuario.setBorder(null);
        getContentPane().add(txtusuario);
        txtusuario.setBounds(960, 220, 240, 60);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(790, 340, 130, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Iniciar Sesión");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(920, 100, 240, 40);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel9.setText("Usuario");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(810, 180, 100, 30);

        jSeparator1.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator1.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(940, 300, 310, 10);

        jSeparator2.setBackground(new java.awt.Color(71, 133, 239));
        jSeparator2.setForeground(new java.awt.Color(71, 133, 239));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(950, 480, 300, 10);

        btnIngresar.setBackground(new java.awt.Color(206, 236, 255));
        btnIngresar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(0, 24, 0));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unicorn_80px.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setAutoscrolls(true);
        btnIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(930, 640, 220, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_lock_100px_1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(800, 380, 110, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_boy_96px.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(800, 220, 100, 100);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_book_philosophy_100px.png"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 0, 130, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 30, 242));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1350, 10, 40, 40);

        txtcontraseñaVisible.setBackground(new java.awt.Color(208, 213, 255));
        txtcontraseñaVisible.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        txtcontraseñaVisible.setBorder(null);
        txtcontraseñaVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaVisibleActionPerformed(evt);
            }
        });
        getContentPane().add(txtcontraseñaVisible);
        txtcontraseñaVisible.setBounds(960, 400, 240, 70);

        txtcontraseñaOculta.setBackground(new java.awt.Color(208, 213, 255));
        txtcontraseñaOculta.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        txtcontraseñaOculta.setBorder(null);
        getContentPane().add(txtcontraseñaOculta);
        txtcontraseñaOculta.setBounds(960, 400, 230, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_key_2_48px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(900, 530, 60, 60);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Mostrar Contraseña");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(980, 540, 180, 40);

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(910, 140, 260, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("x");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1230, 10, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGIN 1300X1050.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 2, 220), 1, true));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 1000);

        setSize(new java.awt.Dimension(1300, 1000));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        String [] usuarios={"admin","directora"};
       String [] contraseñas=new String[2];
       contraseñas[0]="peru123";
       contraseñas[1]="felicidad";
       String user=txtusuario.getText();
       String password=txtcontraseñaVisible.getText();
       boolean mensaje=false;
       for(int i=0;i<usuarios.length;i++){
           if(usuarios[i].equals(user)&&contraseñas[i].equals(password)){
              mensaje=true;
              JOptionPane.showMessageDialog(null,"Bienvenido "+user,"Acceso correcto",1);
              Menú frm2=new Menú();
              frm2.setVisible(true);
              dispose();
           }
       }
       if(!mensaje){
           JOptionPane.showMessageDialog(null,"Usuario o Contraseña incorrecta","ERROR!!",0);
       }
       
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int resp = JOptionPane.showConfirmDialog(this,"Esta segur@ de salir? ","Sistema",JOptionPane.YES_NO_OPTION );
                if(resp == JOptionPane.YES_OPTION){
                   System.exit(0);
                }
                else{
                    return;
                }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed

        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        

        this.setLocation(this.getLocation().x+evt.getX()-x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void txtcontraseñaVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaVisibleActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
        if(mostrar){
        txtcontraseñaVisible.setVisible(true);
        txtcontraseñaOculta.setVisible(false);
        txtcontraseñaVisible.setText(txtcontraseñaOculta.getText());
        mostrar=false;
        }else{
        txtcontraseñaVisible.setVisible(false);
        txtcontraseñaOculta.setVisible(true);
       txtcontraseñaOculta.setText(txtcontraseñaVisible.getText());
        mostrar=true;
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        
        int resp = JOptionPane.showConfirmDialog(this,"Esta segur@ de salir? ","Sistema",JOptionPane.YES_NO_OPTION );
                if(resp == JOptionPane.YES_OPTION){
                   System.exit(0);
                }
                else{
                    return;
                }
                
    }//GEN-LAST:event_jLabel11MouseClicked
int xx,xy;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtcontraseñaOculta;
    private javax.swing.JPasswordField txtcontraseñaVisible;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
